/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using STEP.node;

namespace STEP.lexer {

internal class PushbackReader {
  private TextReader reader;
  private Stack stack = new Stack ();


  internal PushbackReader (TextReader reader)
  {
    this.reader = reader;
  }

  internal int Peek ()
  {
    if ( stack.Count > 0 ) return (int)stack.Peek();
    return reader.Peek();
  }

  internal int Read ()
  {
    if ( stack.Count > 0 ) return (int)stack.Pop();
    return reader.Read();
  }

  internal void Unread (int v)
  {
    stack.Push (v);
  }
}

public class LexerException : ApplicationException
{
    public LexerException(String message) : base (message)
    {
    }
}

public class Lexer
{
    protected Token token;
    protected State currentState = State.INITIAL;

    private PushbackReader input;
    private int line;
    private int pos;
    private bool cr;
    private bool eof;
    private StringBuilder text = new StringBuilder();

    protected virtual void Filter()
    {
    }

    public Lexer(TextReader input)
    {
        this.input = new PushbackReader(input);
    }

    public virtual Token Peek()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        return token;
    }

    public virtual Token Next()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected virtual Token GetToken()
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = Lexer.gotoTable[currentState.id()];
        int[] accept = Lexer.accept[currentState.id()];
        text.Length = 0;

        while(true)
        {
            int c = GetChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.Append((char) c);
                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.Length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.Length;
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = New0(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = New1(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = New2(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = New3(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = New4(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = New5(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = New6(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = New7(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = New8(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = New9(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = New10(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = New11(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = New12(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = New13(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = New14(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = New15(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = New16(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = New17(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = New18(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = New19(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = New20(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = New21(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = New22(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = New23(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = New24(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = New25(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = New26(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = New27(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = New28(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = New29(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = New30(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = New31(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = New32(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = New33(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = New34(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            Token token = New35(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            Token token = New36(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            Token token = New37(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            Token token = New38(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            Token token = New39(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            Token token = New40(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            Token token = New41(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            Token token = New42(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            Token token = New43(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            Token token = New44(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 45:
                        {
                            Token token = New45(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 46:
                        {
                            Token token = New46(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 47:
                        {
                            Token token = New47(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 48:
                        {
                            Token token = New48(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 49:
                        {
                            Token token = New49(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 50:
                        {
                            Token token = New50(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 51:
                        {
                            Token token = New51(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 52:
                        {
                            Token token = New52(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 53:
                        {
                            Token token = New53(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 54:
                        {
                            Token token = New54(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 55:
                        {
                            Token token = New55(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 56:
                        {
                            Token token = New56(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 57:
                        {
                            Token token = New57(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.Length > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    private Token New0(String text, int line, int pos) { return new TLparen(text, line, pos); }
    private Token New1(String text, int line, int pos) { return new TRparen(text, line, pos); }
    private Token New2(String text, int line, int pos) { return new TLbrack(text, line, pos); }
    private Token New3(String text, int line, int pos) { return new TRbrack(text, line, pos); }
    private Token New4(String text, int line, int pos) { return new TNumliteral(text, line, pos); }
    private Token New5(String text, int line, int pos) { return new TStrliteral(text, line, pos); }
    private Token New6(String text, int line, int pos) { return new TBoolliteral(text, line, pos); }
    private Token New7(String text, int line, int pos) { return new TId(text, line, pos); }
    private Token New8(String text, int line, int pos) { return new TAssign(text, line, pos); }
    private Token New9(String text, int line, int pos) { return new TPlus(text, line, pos); }
    private Token New10(String text, int line, int pos) { return new TMinus(text, line, pos); }
    private Token New11(String text, int line, int pos) { return new TDivide(text, line, pos); }
    private Token New12(String text, int line, int pos) { return new TMult(text, line, pos); }
    private Token New13(String text, int line, int pos) { return new TPow(text, line, pos); }
    private Token New14(String text, int line, int pos) { return new TGrthan(text, line, pos); }
    private Token New15(String text, int line, int pos) { return new TGrthaneq(text, line, pos); }
    private Token New16(String text, int line, int pos) { return new TLthan(text, line, pos); }
    private Token New17(String text, int line, int pos) { return new TLthaneq(text, line, pos); }
    private Token New18(String text, int line, int pos) { return new TEq(text, line, pos); }
    private Token New19(String text, int line, int pos) { return new TNeq(text, line, pos); }
    private Token New20(String text, int line, int pos) { return new TNeg(text, line, pos); }
    private Token New21(String text, int line, int pos) { return new TNl(text, line, pos); }
    private Token New22(String text, int line, int pos) { return new TWhitespace(text, line, pos); }
    private Token New23(String text, int line, int pos) { return new TComma(text, line, pos); }
    private Token New24(String text, int line, int pos) { return new TSetup(text, line, pos); }
    private Token New25(String text, int line, int pos) { return new TEndsetup(text, line, pos); }
    private Token New26(String text, int line, int pos) { return new TLoop(text, line, pos); }
    private Token New27(String text, int line, int pos) { return new TEndloop(text, line, pos); }
    private Token New28(String text, int line, int pos) { return new TFunction(text, line, pos); }
    private Token New29(String text, int line, int pos) { return new TEndfunction(text, line, pos); }
    private Token New30(String text, int line, int pos) { return new TFunctions(text, line, pos); }
    private Token New31(String text, int line, int pos) { return new TEndfunctions(text, line, pos); }
    private Token New32(String text, int line, int pos) { return new TBlank(text, line, pos); }
    private Token New33(String text, int line, int pos) { return new TNumber(text, line, pos); }
    private Token New34(String text, int line, int pos) { return new TString(text, line, pos); }
    private Token New35(String text, int line, int pos) { return new TBoolean(text, line, pos); }
    private Token New36(String text, int line, int pos) { return new TIf(text, line, pos); }
    private Token New37(String text, int line, int pos) { return new TEndif(text, line, pos); }
    private Token New38(String text, int line, int pos) { return new TElse(text, line, pos); }
    private Token New39(String text, int line, int pos) { return new TContinue(text, line, pos); }
    private Token New40(String text, int line, int pos) { return new TBreak(text, line, pos); }
    private Token New41(String text, int line, int pos) { return new TRepeatwhile(text, line, pos); }
    private Token New42(String text, int line, int pos) { return new TEndwhile(text, line, pos); }
    private Token New43(String text, int line, int pos) { return new TRepeatfor(text, line, pos); }
    private Token New44(String text, int line, int pos) { return new TEndfor(text, line, pos); }
    private Token New45(String text, int line, int pos) { return new TTo(text, line, pos); }
    private Token New46(String text, int line, int pos) { return new TIncreaseby(text, line, pos); }
    private Token New47(String text, int line, int pos) { return new TDecreaseby(text, line, pos); }
    private Token New48(String text, int line, int pos) { return new TSwitch(text, line, pos); }
    private Token New49(String text, int line, int pos) { return new TEndswitch(text, line, pos); }
    private Token New50(String text, int line, int pos) { return new TWhen(text, line, pos); }
    private Token New51(String text, int line, int pos) { return new TDo(text, line, pos); }
    private Token New52(String text, int line, int pos) { return new TFallthrough(text, line, pos); }
    private Token New53(String text, int line, int pos) { return new TOtherwisedo(text, line, pos); }
    private Token New54(String text, int line, int pos) { return new TReturn(text, line, pos); }
    private Token New55(String text, int line, int pos) { return new TAnd(text, line, pos); }
    private Token New56(String text, int line, int pos) { return new TOr(text, line, pos); }
    private Token New57(String text, int line, int pos) { return new TConstant(text, line, pos); }

    private int GetChar()
    {
        if(eof)
        {
            return -1;
        }

        int result = input.Read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void PushBack(int acceptLength)
    {
        int length = text.Length;
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }
    }


    protected virtual void Unread(Token token)
    {
        String text = token.Text;
        int length = text.Length;

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }

        pos = token.Pos - 1;
        line = token.Line - 1;
    }

    private string GetText(int acceptLength)
    {
        StringBuilder s = new StringBuilder(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.Append(text[i]);
        }

        return s.ToString();
    }

    private static int[][][][] gotoTable = {
      new int[][][] {
        new int[][] {
          new int[] {9, 9, 1},
          new int[] {10, 10, 2},
          new int[] {13, 13, 3},
          new int[] {32, 32, 4},
          new int[] {33, 33, 5},
          new int[] {40, 40, 6},
          new int[] {41, 41, 7},
          new int[] {42, 42, 8},
          new int[] {43, 43, 9},
          new int[] {44, 44, 10},
          new int[] {45, 45, 11},
          new int[] {47, 47, 12},
          new int[] {48, 57, 13},
          new int[] {60, 60, 14},
          new int[] {61, 61, 15},
          new int[] {62, 62, 16},
          new int[] {65, 90, 17},
          new int[] {91, 91, 18},
          new int[] {92, 92, 19},
          new int[] {93, 93, 20},
          new int[] {94, 94, 21},
          new int[] {95, 95, 22},
          new int[] {97, 97, 23},
          new int[] {98, 98, 24},
          new int[] {99, 99, 25},
          new int[] {100, 100, 26},
          new int[] {101, 101, 27},
          new int[] {102, 102, 28},
          new int[] {103, 104, 29},
          new int[] {105, 105, 30},
          new int[] {106, 107, 29},
          new int[] {108, 108, 31},
          new int[] {109, 109, 29},
          new int[] {110, 110, 32},
          new int[] {111, 111, 33},
          new int[] {112, 113, 29},
          new int[] {114, 114, 34},
          new int[] {115, 115, 35},
          new int[] {116, 116, 36},
          new int[] {117, 118, 29},
          new int[] {119, 119, 37},
          new int[] {120, 122, 29},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {9, 9, 1},
          new int[] {10, 10, 38},
          new int[] {13, 32, -2},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
          new int[] {61, 61, 39},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {46, 46, 40},
          new int[] {48, 57, 13},
        },
        new int[][] {
          new int[] {61, 61, 41},
        },
        new int[][] {
          new int[] {61, 61, 42},
        },
        new int[][] {
          new int[] {61, 61, 43},
        },
        new int[][] {
          new int[] {48, 57, 44},
          new int[] {65, 90, 45},
          new int[] {95, 95, 46},
          new int[] {97, 122, 47},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {34, 34, 48},
          new int[] {114, 114, 49},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 109, 47},
          new int[] {110, 110, 50},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 107, 47},
          new int[] {108, 108, 51},
          new int[] {109, 110, 47},
          new int[] {111, 111, 52},
          new int[] {112, 113, 47},
          new int[] {114, 114, 53},
          new int[] {115, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 110, 47},
          new int[] {111, 111, 54},
          new int[] {112, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 100, 47},
          new int[] {101, 101, 55},
          new int[] {102, 110, 47},
          new int[] {111, 111, 56},
          new int[] {112, 122, 47},
        },
        new int[][] {
          new int[] {48, 107, -26},
          new int[] {108, 108, 57},
          new int[] {109, 109, 47},
          new int[] {110, 110, 58},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 97, 59},
          new int[] {98, 116, 47},
          new int[] {117, 117, 60},
          new int[] {118, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 101, 47},
          new int[] {102, 102, 61},
          new int[] {103, 109, 47},
          new int[] {110, 110, 62},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 110, -27},
          new int[] {111, 111, 63},
          new int[] {112, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 116, 47},
          new int[] {117, 117, 64},
          new int[] {118, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 113, 47},
          new int[] {114, 114, 65},
          new int[] {115, 115, 47},
          new int[] {116, 116, 66},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 67},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 68},
          new int[] {102, 115, 47},
          new int[] {116, 116, 69},
          new int[] {117, 118, 47},
          new int[] {119, 119, 70},
          new int[] {120, 122, 47},
        },
        new int[][] {
          new int[] {48, 110, -27},
          new int[] {111, 111, 71},
          new int[] {112, 113, 47},
          new int[] {114, 114, 72},
          new int[] {115, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 103, 47},
          new int[] {104, 104, 73},
          new int[] {105, 122, 47},
        },
        new int[][] {
          new int[] {9, 32, -2},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 57, 74},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {46, 46, 75},
        },
        new int[][] {
          new int[] {63, 63, 76},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 99, 47},
          new int[] {100, 100, 77},
          new int[] {101, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 97, 78},
          new int[] {98, 122, 47},
        },
        new int[][] {
          new int[] {48, 110, -27},
          new int[] {111, 111, 79},
          new int[] {112, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 80},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 81},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 98, 47},
          new int[] {99, 99, 82},
          new int[] {100, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 114, 47},
          new int[] {115, 115, 83},
          new int[] {116, 122, 47},
        },
        new int[][] {
          new int[] {48, 99, -52},
          new int[] {100, 100, 84},
          new int[] {101, 122, 47},
        },
        new int[][] {
          new int[] {48, 107, -26},
          new int[] {108, 108, 85},
          new int[] {109, 122, 47},
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 86},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 98, -57},
          new int[] {99, 99, 87},
          new int[] {100, 122, 47},
        },
        new int[][] {
          new int[] {48, 110, -27},
          new int[] {111, 111, 88},
          new int[] {112, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 108, 47},
          new int[] {109, 109, 89},
          new int[] {110, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 103, -39},
          new int[] {104, 104, 90},
          new int[] {105, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 111, 47},
          new int[] {112, 112, 91},
          new int[] {113, 115, 47},
          new int[] {116, 116, 92},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 115, 47},
          new int[] {116, 116, 93},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 113, -35},
          new int[] {114, 114, 94},
          new int[] {115, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 104, 47},
          new int[] {105, 105, 95},
          new int[] {106, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 116, -34},
          new int[] {117, 117, 96},
          new int[] {118, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 97},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 57, 74},
        },
        new int[][] {
          new int[] {42, 42, 98},
        },
        new int[][] {
          new int[] {92, 92, 99},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 100},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 107, -26},
          new int[] {108, 108, 101},
          new int[] {109, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 97, 102},
          new int[] {98, 122, 47},
        },
        new int[][] {
          new int[] {48, 114, -59},
          new int[] {115, 115, 103},
          new int[] {116, 116, 104},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 113, -35},
          new int[] {114, 114, 105},
          new int[] {115, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 106},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {32, 32, 107},
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 107, -26},
          new int[] {108, 108, 108},
          new int[] {109, 114, 47},
          new int[] {115, 115, 109},
          new int[] {116, 122, 47},
        },
        new int[][] {
          new int[] {48, 98, -57},
          new int[] {99, 99, 110},
          new int[] {100, 122, 47},
        },
        new int[][] {
          new int[] {48, 113, -35},
          new int[] {114, 114, 111},
          new int[] {115, 122, 47},
        },
        new int[][] {
          new int[] {48, 111, -69},
          new int[] {112, 112, 112},
          new int[] {113, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 97, 47},
          new int[] {98, 98, 113},
          new int[] {99, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 114},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 115},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 116, -34},
          new int[] {117, 117, 116},
          new int[] {118, 122, 47},
        },
        new int[][] {
          new int[] {48, 116, -34},
          new int[] {117, 117, 117},
          new int[] {118, 122, 47},
        },
        new int[][] {
          new int[] {48, 104, -72},
          new int[] {105, 105, 118},
          new int[] {106, 122, 47},
        },
        new int[][] {
          new int[] {48, 115, -70},
          new int[] {116, 116, 119},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 120},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 121},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {92, 92, 122},
        },
        new int[][] {
          new int[] {110, 110, 123},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 106, 47},
          new int[] {107, 107, 124},
          new int[] {108, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 125},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 106, -102},
          new int[] {107, 107, 126},
          new int[] {108, 122, 47},
        },
        new int[][] {
          new int[] {48, 115, -70},
          new int[] {116, 116, 127},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 104, -72},
          new int[] {105, 105, 128},
          new int[] {106, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 129},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {102, 102, 130},
          new int[] {105, 105, 131},
          new int[] {108, 108, 132},
          new int[] {115, 115, 133},
          new int[] {119, 119, 134},
        },
        new int[][] {
          new int[] {48, 115, -70},
          new int[] {116, 116, 135},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 136},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 115, -70},
          new int[] {116, 116, 137},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 138},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 139},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 113, -35},
          new int[] {114, 114, 140},
          new int[] {115, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 97, 141},
          new int[] {98, 122, 47},
        },
        new int[][] {
          new int[] {48, 113, -35},
          new int[] {114, 114, 142},
          new int[] {115, 122, 47},
        },
        new int[][] {
          new int[] {48, 111, -69},
          new int[] {112, 112, 143},
          new int[] {113, 122, 47},
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 144},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 98, -57},
          new int[] {99, 99, 145},
          new int[] {100, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {34, 34, 146},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 97, 147},
          new int[] {98, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 97, 148},
          new int[] {98, 122, 47},
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 149},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 97, 150},
          new int[] {98, 122, 47},
        },
        new int[][] {
          new int[] {111, 111, 151},
          new int[] {117, 117, 152},
        },
        new int[][] {
          new int[] {102, 102, 153},
        },
        new int[][] {
          new int[] {111, 111, 154},
        },
        new int[][] {
          new int[] {101, 101, 155},
          new int[] {119, 119, 156},
        },
        new int[][] {
          new int[] {104, 104, 157},
        },
        new int[][] {
          new int[] {48, 103, -39},
          new int[] {104, 104, 158},
          new int[] {105, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 104, -72},
          new int[] {105, 105, 159},
          new int[] {106, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 97, 160},
          new int[] {98, 122, 47},
        },
        new int[][] {
          new int[] {48, 113, -35},
          new int[] {114, 114, 161},
          new int[] {115, 122, 47},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 118, 47},
          new int[] {119, 119, 162},
          new int[] {120, 122, 47},
        },
        new int[][] {
          new int[] {48, 115, -70},
          new int[] {116, 116, 163},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 164},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 95, -19},
          new int[] {97, 102, 47},
          new int[] {103, 103, 165},
          new int[] {104, 122, 47},
        },
        new int[][] {
          new int[] {48, 103, -39},
          new int[] {104, 104, 166},
          new int[] {105, 122, 47},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 167},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 168},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 116, -34},
          new int[] {117, 117, 169},
          new int[] {118, 122, 47},
        },
        new int[][] {
          new int[] {48, 114, -59},
          new int[] {115, 115, 170},
          new int[] {116, 122, 47},
        },
        new int[][] {
          new int[] {114, 114, 171},
        },
        new int[][] {
          new int[] {110, 110, 172},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {111, 111, 173},
        },
        new int[][] {
          new int[] {116, 116, 174},
        },
        new int[][] {
          new int[] {105, 105, 175},
        },
        new int[][] {
          new int[] {105, 105, 176},
        },
        new int[][] {
          new int[] {48, 113, -35},
          new int[] {114, 114, 177},
          new int[] {115, 122, 47},
        },
        new int[][] {
          new int[] {48, 110, -27},
          new int[] {111, 111, 178},
          new int[] {112, 122, 47},
        },
        new int[][] {
          new int[] {48, 114, -59},
          new int[] {115, 115, 179},
          new int[] {116, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 104, -72},
          new int[] {105, 105, 180},
          new int[] {106, 122, 47},
        },
        new int[][] {
          new int[] {32, 32, 181},
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 115, -70},
          new int[] {116, 116, 182},
          new int[] {117, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 183},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 184},
          new int[] {102, 122, 47},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {99, 99, 185},
        },
        new int[][] {
          new int[] {112, 112, 186},
        },
        new int[][] {
          new int[] {117, 117, 187},
        },
        new int[][] {
          new int[] {116, 116, 188},
        },
        new int[][] {
          new int[] {108, 108, 189},
        },
        new int[][] {
          new int[] {48, 110, -27},
          new int[] {111, 111, 190},
          new int[] {112, 122, 47},
        },
        new int[][] {
          new int[] {48, 109, -25},
          new int[] {110, 110, 191},
          new int[] {111, 122, 47},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 192},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {48, 114, -59},
          new int[] {115, 115, 193},
          new int[] {116, 122, 47},
        },
        new int[][] {
          new int[] {102, 102, 194},
          new int[] {119, 119, 195},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {32, 32, 196},
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {116, 116, 197},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {112, 112, 198},
        },
        new int[][] {
          new int[] {99, 99, 199},
        },
        new int[][] {
          new int[] {101, 101, 200},
        },
        new int[][] {
          new int[] {48, 116, -34},
          new int[] {117, 117, 201},
          new int[] {118, 122, 47},
        },
        new int[][] {
          new int[] {48, 114, -59},
          new int[] {115, 115, 202},
          new int[] {116, 122, 47},
        },
        new int[][] {
          new int[] {32, 32, 203},
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {48, 100, -28},
          new int[] {101, 101, 204},
          new int[] {102, 122, 47},
        },
        new int[][] {
          new int[] {111, 111, 205},
        },
        new int[][] {
          new int[] {104, 104, 206},
        },
        new int[][] {
          new int[] {98, 98, 207},
        },
        new int[][] {
          new int[] {105, 105, 208},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {104, 104, 209},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 102, -146},
          new int[] {103, 103, 210},
          new int[] {104, 122, 47},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {98, 98, 211},
        },
        new int[][] {
          new int[] {32, 32, 212},
          new int[] {48, 122, -19},
        },
        new int[][] {
          new int[] {114, 114, 213},
        },
        new int[][] {
          new int[] {105, 105, 214},
        },
        new int[][] {
          new int[] {121, 121, 215},
        },
        new int[][] {
          new int[] {111, 111, 216},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 103, -39},
          new int[] {104, 104, 217},
          new int[] {105, 122, 47},
        },
        new int[][] {
          new int[] {121, 121, 218},
        },
        new int[][] {
          new int[] {100, 100, 219},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {108, 108, 220},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {110, 110, 221},
        },
        new int[][] {
          new int[] {48, 122, -19},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {111, 111, 222},
        },
        new int[][] {
          new int[] {101, 101, 223},
        },
        new int[][] {
          new int[] {115, 115, 224},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
      },
    };

    private static int[][] accept = {
      new int[] {
        -1, 22, 22, 22, 22, 20, 0, 1, 12, 9, 23, 10, 11, 4, 16, 8, 
        14, 7, 2, -1, 3, 13, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 
        7, 7, 7, 7, 7, 7, 22, 19, 4, 17, 18, 15, 7, 7, 7, 7, 
        -1, -1, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, -1, -1, 7, 7, 7, 
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 
        7, 7, -1, -1, 7, 7, 7, 7, 7, 7, 7, -1, 7, 7, 7, 7, 
        7, 7, 7, 7, 7, 7, 7, 7, 6, 7, -1, 21, 7, 7, 7, 7, 
        7, 7, -1, -1, -1, -1, -1, 7, 6, 7, 7, 7, 7, 7, 7, 7, 
        7, 7, 5, 7, 7, 7, 7, -1, -1, 37, -1, -1, -1, -1, 7, 7, 
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 44, -1, -1, -1, -1, 
        -1, 7, 7, 7, 7, -1, 7, 7, 7, -1, 27, -1, -1, -1, 7, 7, 
        7, 7, -1, -1, -1, -1, 25, -1, 42, 7, 7, -1, 7, -1, -1, -1, 
        -1, 49, 7, -1, -1, 43, -1, 47, -1, 7, 46, -1, -1, 29, 53, 41, 
        31, 
      },
    };

    public class State
    {
        public static State INITIAL = new State(0);

        private int _id;

        private State(int _id)
        {
            this._id = _id;
        }

        public int id()
        {
            return _id;
        }
    }
}
}
