//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/Mikkel/Documents/Codebase/STEP/STEP/ANTLR gens\STEP.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISTEPListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class STEPBaseListener : ISTEPListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] STEPParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] STEPParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.setuploop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetuploop([NotNull] STEPParser.SetuploopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.setuploop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetuploop([NotNull] STEPParser.SetuploopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetup([NotNull] STEPParser.SetupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.setup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetup([NotNull] STEPParser.SetupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop([NotNull] STEPParser.LoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop([NotNull] STEPParser.LoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.variables"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariables([NotNull] STEPParser.VariablesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.variables"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariables([NotNull] STEPParser.VariablesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.var_or_nl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_or_nl([NotNull] STEPParser.Var_or_nlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.var_or_nl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_or_nl([NotNull] STEPParser.Var_or_nlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctions([NotNull] STEPParser.FunctionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.functions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctions([NotNull] STEPParser.FunctionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.funcdcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncdcl([NotNull] STEPParser.FuncdclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.funcdcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncdcl([NotNull] STEPParser.FuncdclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.funcdcl_or_nl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncdcl_or_nl([NotNull] STEPParser.Funcdcl_or_nlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.funcdcl_or_nl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncdcl_or_nl([NotNull] STEPParser.Funcdcl_or_nlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.brackets"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBrackets([NotNull] STEPParser.BracketsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.brackets"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBrackets([NotNull] STEPParser.BracketsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] STEPParser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] STEPParser.ParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.params_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams_content([NotNull] STEPParser.Params_contentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.params_content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams_content([NotNull] STEPParser.Params_contentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.params_multi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams_multi([NotNull] STEPParser.Params_multiContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.params_multi"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams_multi([NotNull] STEPParser.Params_multiContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] STEPParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] STEPParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.paramstype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamstype([NotNull] STEPParser.ParamstypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.paramstype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamstype([NotNull] STEPParser.ParamstypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] STEPParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] STEPParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.stmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmts([NotNull] STEPParser.StmtsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.stmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmts([NotNull] STEPParser.StmtsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.loop_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop_stmt([NotNull] STEPParser.Loop_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.loop_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop_stmt([NotNull] STEPParser.Loop_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.loop_stmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop_stmts([NotNull] STEPParser.Loop_stmtsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.loop_stmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop_stmts([NotNull] STEPParser.Loop_stmtsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.loopifbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopifbody([NotNull] STEPParser.LoopifbodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.loopifbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopifbody([NotNull] STEPParser.LoopifbodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfstmt([NotNull] STEPParser.IfstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.ifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfstmt([NotNull] STEPParser.IfstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.elseifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseifstmt([NotNull] STEPParser.ElseifstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.elseifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseifstmt([NotNull] STEPParser.ElseifstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.elsestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElsestmt([NotNull] STEPParser.ElsestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.elsestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElsestmt([NotNull] STEPParser.ElsestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.loopifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopifstmt([NotNull] STEPParser.LoopifstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.loopifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopifstmt([NotNull] STEPParser.LoopifstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.loopelseifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopelseifstmt([NotNull] STEPParser.LoopelseifstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.loopelseifstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopelseifstmt([NotNull] STEPParser.LoopelseifstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.loopelsestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopelsestmt([NotNull] STEPParser.LoopelsestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.loopelsestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopelsestmt([NotNull] STEPParser.LoopelsestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.whilestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhilestmt([NotNull] STEPParser.WhilestmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.whilestmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhilestmt([NotNull] STEPParser.WhilestmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.forstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForstmt([NotNull] STEPParser.ForstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.forstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForstmt([NotNull] STEPParser.ForstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.for_iter_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_iter_opt([NotNull] STEPParser.For_iter_optContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.for_iter_opt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_iter_opt([NotNull] STEPParser.For_iter_optContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.assstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssstmt([NotNull] STEPParser.AssstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.assstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssstmt([NotNull] STEPParser.AssstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.funccall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunccall([NotNull] STEPParser.FunccallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.funccall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunccall([NotNull] STEPParser.FunccallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.params_options"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams_options([NotNull] STEPParser.Params_optionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.params_options"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams_options([NotNull] STEPParser.Params_optionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.multi_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulti_expr([NotNull] STEPParser.Multi_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.multi_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulti_expr([NotNull] STEPParser.Multi_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.retstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRetstmt([NotNull] STEPParser.RetstmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.retstmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRetstmt([NotNull] STEPParser.RetstmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.arrindex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrindex([NotNull] STEPParser.ArrindexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.arrindex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrindex([NotNull] STEPParser.ArrindexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] STEPParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] STEPParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] STEPParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] STEPParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] STEPParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] STEPParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] STEPParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] STEPParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] STEPParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] STEPParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.logicexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicexpr([NotNull] STEPParser.LogicexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.logicexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicexpr([NotNull] STEPParser.LogicexprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.logicequal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicequal([NotNull] STEPParser.LogicequalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.logicequal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicequal([NotNull] STEPParser.LogicequalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.logiccomp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogiccomp([NotNull] STEPParser.LogiccompContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.logiccomp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogiccomp([NotNull] STEPParser.LogiccompContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.logiccompop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogiccompop([NotNull] STEPParser.LogiccompopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.logiccompop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogiccompop([NotNull] STEPParser.LogiccompopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.logicvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicvalue([NotNull] STEPParser.LogicvalueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.logicvalue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicvalue([NotNull] STEPParser.LogicvalueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.vardcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVardcl([NotNull] STEPParser.VardclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.vardcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVardcl([NotNull] STEPParser.VardclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.var_options"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_options([NotNull] STEPParser.Var_optionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.var_options"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_options([NotNull] STEPParser.Var_optionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.numdcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumdcl([NotNull] STEPParser.NumdclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.numdcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumdcl([NotNull] STEPParser.NumdclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.stringdcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringdcl([NotNull] STEPParser.StringdclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.stringdcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringdcl([NotNull] STEPParser.StringdclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.booldcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooldcl([NotNull] STEPParser.BooldclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.booldcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooldcl([NotNull] STEPParser.BooldclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.pindcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPindcl([NotNull] STEPParser.PindclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.pindcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPindcl([NotNull] STEPParser.PindclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.pinmode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPinmode([NotNull] STEPParser.PinmodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.pinmode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPinmode([NotNull] STEPParser.PinmodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.pintype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPintype([NotNull] STEPParser.PintypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.pintype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPintype([NotNull] STEPParser.PintypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.arrdcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrdcl([NotNull] STEPParser.ArrdclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.arrdcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrdcl([NotNull] STEPParser.ArrdclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.arrdclrhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrdclrhs([NotNull] STEPParser.ArrdclrhsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.arrdclrhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrdclrhs([NotNull] STEPParser.ArrdclrhsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="STEPParser.arrsizedcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrsizedcl([NotNull] STEPParser.ArrsizedclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="STEPParser.arrsizedcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrsizedcl([NotNull] STEPParser.ArrsizedclContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
